import "server-only";

import type {
  SupabaseClient,
} from "@supabase/supabase-js";


export type ClaimedAttendanceEmail = {
  id: string;
  student_id: string;
  session_id: string | null;
  notification_type: string;
  recipient: string;
  subject: string;
  message: string;
  attempts: number;
};


type ResendResponse = {
  id?: string;
  message?: string;
  name?: string;
  statusCode?: number;
};


export type AttendanceEmailDeliveryResult = {
  outboxId: string;

  status:
    | "Sent"
    | "Failed";

  providerMessageId?: string;

  retryable?: boolean;

  error?: string;
};


type DeliverAttendanceEmailOptions = {
  admin: SupabaseClient;

  claimed:
    ClaimedAttendanceEmail;

  resendApiKey: string;

  emailFrom: string;
};


const escapeHtml = (
  value: string
) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");


const emailHtml = (
  subject: string,
  message: string
) => {
  const safeSubject =
    escapeHtml(subject);

  const safeMessage =
    escapeHtml(message);

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1"
  />
  <title>${safeSubject}</title>
</head>

<body
  style="
    margin:0;
    padding:0;
    background:#f4f6f8;
    font-family:
      Inter,
      -apple-system,
      BlinkMacSystemFont,
      'Segoe UI',
      sans-serif;
    color:#172033;
  "
>
  <table
    role="presentation"
    width="100%"
    cellspacing="0"
    cellpadding="0"
    border="0"
    style="
      width:100%;
      background:#f4f6f8;
      padding:32px 16px;
    "
  >
    <tr>
      <td align="center">

        <table
          role="presentation"
          width="100%"
          cellspacing="0"
          cellpadding="0"
          border="0"
          style="
            max-width:620px;
            background:#ffffff;
            border-radius:18px;
            overflow:hidden;
            border:1px solid #e5e9f0;
          "
        >

          <tr>
            <td
              style="
                padding:28px 30px 20px;
                background:#172033;
                color:#ffffff;
              "
            >
              <div
                style="
                  font-size:13px;
                  font-weight:700;
                  letter-spacing:.12em;
                  text-transform:uppercase;
                  opacity:.75;
                "
              >
                CampusConnect
              </div>

              <div
                style="
                  margin-top:10px;
                  font-size:24px;
                  line-height:1.3;
                  font-weight:750;
                "
              >
                ${safeSubject}
              </div>
            </td>
          </tr>

          <tr>
            <td
              style="
                padding:30px;
              "
            >
              <p
                style="
                  margin:0;
                  font-size:16px;
                  line-height:1.75;
                  color:#354158;
                "
              >
                ${safeMessage}
              </p>

              <div
                style="
                  margin-top:28px;
                  padding-top:20px;
                  border-top:1px solid #e8ebf0;
                  font-size:13px;
                  line-height:1.6;
                  color:#778197;
                "
              >
                This is an automated attendance notification
                generated by CampusConnect.
              </div>
            </td>
          </tr>

        </table>

      </td>
    </tr>
  </table>
</body>
</html>`;
};


async function recordFailure(
  admin: SupabaseClient,
  outboxId: string,
  message: string,
  retryable: boolean
): Promise<void> {
  const rpc =
    retryable
      ? "fail_attendance_email_delivery"
      : "terminal_fail_attendance_email_delivery";

  const {
    data,
    error,
  } =
    await admin.rpc(
      rpc,
      {
        target_outbox_id:
          outboxId,

        failure_message:
          message.slice(
            0,
            1500
          ),
      }
    );

  if (
    error ||
    data !== true
  ) {
    console.error(
      retryable
        ? "Unable to record retryable attendance email failure:"
        : "Unable to record terminal attendance email failure:",
      error ||
        "Database rejected the failure transition."
    );
  }
}


export async function deliverClaimedAttendanceEmail(
  options:
    DeliverAttendanceEmailOptions
): Promise<AttendanceEmailDeliveryResult> {
  const {
    admin,
    claimed,
    resendApiKey,
    emailFrom,
  } = options;

  const idempotencyKey =
    `attendance-${claimed.id}`;

  try {
    const response =
      await fetch(
        "https://api.resend.com/emails",
        {
          method: "POST",

          headers: {
            Authorization:
              `Bearer ${resendApiKey}`,

            "Content-Type":
              "application/json",

            "Idempotency-Key":
              idempotencyKey,
          },

          body:
            JSON.stringify({
              from:
                emailFrom,

              to: [
                claimed.recipient,
              ],

              subject:
                claimed.subject,

              text:
                claimed.message,

              html:
                emailHtml(
                  claimed.subject,
                  claimed.message
                ),
            }),
        }
      );

    let provider:
      ResendResponse = {};

    try {
      provider =
        (await response.json()) as
          ResendResponse;
    } catch {
      provider = {};
    }

    if (
      !response.ok ||
      !provider.id
    ) {
      const providerError =
        String(
          provider.message ||
          provider.name ||
          `Email provider returned HTTP ${response.status}.`
        ).slice(
          0,
          1500
        );

      /*
       * Retry:
       * - 408 timeout
       * - 425 too early
       * - 429 rate limit
       * - 5xx provider/server failure
       * - 2xx without provider ID
       *
       * Other non-success responses are terminal.
       */
      const retryable =
        response.ok ||
        response.status === 408 ||
        response.status === 425 ||
        response.status === 429 ||
        (
          response.status >= 500 &&
          response.status <= 599
        );

      await recordFailure(
        admin,
        claimed.id,
        providerError,
        retryable
      );

      return {
        outboxId:
          claimed.id,

        status:
          "Failed",

        retryable,

        error:
          providerError,
      };
    }

    const {
      data: completed,
      error: completionError,
    } =
      await admin.rpc(
        "complete_attendance_email_delivery",
        {
          target_outbox_id:
            claimed.id,

          target_provider_message_id:
            provider.id,
        }
      );

    if (
      completionError ||
      completed !== true
    ) {
      /*
       * Provider accepted the email.
       *
       * Do not mark Failed here. Leaving the row Processing
       * allows stale recovery/reconciliation while the stable
       * provider idempotency key protects a later retry.
       */
      console.error(
        "Email sent but database finalization failed:",
        completionError ||
          "Database rejected the completion transition."
      );

      return {
        outboxId:
          claimed.id,

        status:
          "Failed",

        providerMessageId:
          provider.id,

        error:
          "Provider accepted the email, but CampusConnect could not finalize its delivery state.",
      };
    }

    return {
      outboxId:
        claimed.id,

      status:
        "Sent",

      providerMessageId:
        provider.id,
    };
  } catch (error) {
    const message =
      (
        error instanceof Error
          ? error.message
          : "Unknown email delivery error."
      ).slice(
        0,
        1500
      );

    /*
     * Network/runtime exceptions are retryable.
     */
    await recordFailure(
      admin,
      claimed.id,
      message,
      true
    );

    return {
      outboxId:
        claimed.id,

      status:
        "Failed",

      retryable:
        true,

      error:
        message,
    };
  }
}
