-- ============================================================
-- CAMPUSCONNECT AI — PHASE 4 LEARNING RAG FOUNDATION
-- Real learning_resources and profile_documents only.
-- No document text or embeddings are generated by this migration.
-- ============================================================

create extension if not exists vector
with schema extensions;


-- ============================================================
-- INDEXED DOCUMENT REGISTRY
-- ============================================================

create table if not exists public.ai_documents (
  id uuid primary key default gen_random_uuid(),

  owner_id uuid not null
    references auth.users(id)
    on delete cascade,

  source_type text not null
    check (
      source_type in (
        'learning_resource',
        'profile_document'
      )
    ),

  source_id uuid not null,

  visibility text not null
    default 'private'
    check (
      visibility in (
        'private',
        'campus'
      )
    ),

  title text not null
    check (
      char_length(title)
        between 1 and 500
    ),

  subject text not null default '',
  department text not null default '',
  semester text not null default '',
  document_type text not null default '',
  mime_type text not null default '',
  storage_bucket text not null default '',
  storage_path text not null default '',
  source_url text not null default '',

  status text not null
    default 'pending'
    check (
      status in (
        'pending',
        'processing',
        'ready',
        'failed'
      )
    ),

  content_hash text not null default '',
  extracted_character_count integer not null default 0
    check (extracted_character_count >= 0),
  chunk_count integer not null default 0
    check (chunk_count >= 0),
  extraction_error text not null default '',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (
    source_type,
    source_id,
    owner_id
  )
);


-- ============================================================
-- DOCUMENT CHUNKS
-- embedding deliberately has no fixed dimension yet.
-- Groq chat models do not provide an embedding vector through
-- the existing chat-completions configuration. A dimension and
-- vector index will be added only after a real embedding model is
-- configured. PostgreSQL full-text retrieval works immediately.
-- ============================================================

create table if not exists public.ai_document_chunks (
  id uuid primary key default gen_random_uuid(),

  document_id uuid not null
    references public.ai_documents(id)
    on delete cascade,

  owner_id uuid not null
    references auth.users(id)
    on delete cascade,

  chunk_index integer not null
    check (chunk_index >= 0),

  content text not null
    check (
      char_length(content)
        between 1 and 12000
    ),

  token_count integer not null default 0
    check (token_count >= 0),

  metadata jsonb not null
    default '{}'::jsonb,

  embedding extensions.vector,
  embedding_model text not null default '',
  embedding_dimensions integer
    check (
      embedding_dimensions is null
      or embedding_dimensions > 0
    ),

  search_vector tsvector
    generated always as (
      to_tsvector(
        'simple',
        coalesce(content, '')
      )
    ) stored,

  created_at timestamptz not null default now(),

  unique (
    document_id,
    chunk_index
  )
);


-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists
ai_documents_owner_updated_idx
on public.ai_documents(
  owner_id,
  updated_at desc
);

create index if not exists
ai_documents_source_idx
on public.ai_documents(
  source_type,
  source_id
);

create index if not exists
ai_documents_visibility_status_idx
on public.ai_documents(
  visibility,
  status
);

create index if not exists
ai_document_chunks_document_idx
on public.ai_document_chunks(
  document_id,
  chunk_index
);

create index if not exists
ai_document_chunks_owner_idx
on public.ai_document_chunks(
  owner_id
);

create index if not exists
ai_document_chunks_search_idx
on public.ai_document_chunks
using gin(search_vector);


-- ============================================================
-- RLS AND GRANTS
-- ============================================================

alter table public.ai_documents
enable row level security;

alter table public.ai_document_chunks
enable row level security;

revoke all on
  public.ai_documents,
  public.ai_document_chunks
from anon;

grant select, insert, update, delete
on public.ai_documents
to authenticated;

grant select, insert, update, delete
on public.ai_document_chunks
to authenticated;


drop policy if exists
  "Users read permitted AI documents"
on public.ai_documents;

create policy
  "Users read permitted AI documents"
on public.ai_documents
for select
to authenticated
using (
  owner_id = (select auth.uid())
  or visibility = 'campus'
);


drop policy if exists
  "Users create permitted AI documents"
on public.ai_documents;

create policy
  "Users create permitted AI documents"
on public.ai_documents
for insert
to authenticated
with check (
  owner_id = (select auth.uid())
  and (
    visibility = 'private'
    or (
      visibility = 'campus'
      and (
        select public.current_campus_role()
      ) in (
        'Faculty',
        'Coordinator',
        'Placement Cell',
        'Main Admin'
      )
    )
  )
);


drop policy if exists
  "Users update own AI documents"
on public.ai_documents;

create policy
  "Users update own AI documents"
on public.ai_documents
for update
to authenticated
using (
  owner_id = (select auth.uid())
)
with check (
  owner_id = (select auth.uid())
  and (
    visibility = 'private'
    or (
      visibility = 'campus'
      and (
        select public.current_campus_role()
      ) in (
        'Faculty',
        'Coordinator',
        'Placement Cell',
        'Main Admin'
      )
    )
  )
);


drop policy if exists
  "Users delete own AI documents"
on public.ai_documents;

create policy
  "Users delete own AI documents"
on public.ai_documents
for delete
to authenticated
using (
  owner_id = (select auth.uid())
);


drop policy if exists
  "Users read permitted AI chunks"
on public.ai_document_chunks;

create policy
  "Users read permitted AI chunks"
on public.ai_document_chunks
for select
to authenticated
using (
  exists (
    select 1
    from public.ai_documents document
    where document.id = document_id
  )
);


drop policy if exists
  "Users create own AI chunks"
on public.ai_document_chunks;

create policy
  "Users create own AI chunks"
on public.ai_document_chunks
for insert
to authenticated
with check (
  owner_id = (select auth.uid())
  and exists (
    select 1
    from public.ai_documents document
    where
      document.id = document_id
      and document.owner_id =
        (select auth.uid())
  )
);


drop policy if exists
  "Users update own AI chunks"
on public.ai_document_chunks;

create policy
  "Users update own AI chunks"
on public.ai_document_chunks
for update
to authenticated
using (
  owner_id = (select auth.uid())
)
with check (
  owner_id = (select auth.uid())
  and exists (
    select 1
    from public.ai_documents document
    where
      document.id = document_id
      and document.owner_id =
        (select auth.uid())
  )
);


drop policy if exists
  "Users delete own AI chunks"
on public.ai_document_chunks;

create policy
  "Users delete own AI chunks"
on public.ai_document_chunks
for delete
to authenticated
using (
  owner_id = (select auth.uid())
);


-- ============================================================
-- FULL-TEXT RETRIEVAL
-- Security invoker is intentional: caller JWT + RLS apply.
-- ============================================================

create or replace function
public.search_ai_document_chunks(
  p_query text,
  p_match_count integer default 8,
  p_source_id uuid default null
)
returns table (
  chunk_id uuid,
  document_id uuid,
  source_type text,
  source_id uuid,
  title text,
  subject text,
  content text,
  metadata jsonb,
  score real
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    chunk.id,
    document.id,
    document.source_type,
    document.source_id,
    document.title,
    document.subject,
    chunk.content,
    chunk.metadata,
    ts_rank_cd(
      chunk.search_vector,
      websearch_to_tsquery(
        'simple',
        trim(p_query)
      )
    )::real as score
  from public.ai_document_chunks chunk
  join public.ai_documents document
    on document.id = chunk.document_id
  where
    document.status = 'ready'
    and trim(coalesce(p_query, '')) <> ''
    and chunk.search_vector @@
      websearch_to_tsquery(
        'simple',
        trim(p_query)
      )
    and (
      p_source_id is null
      or document.source_id = p_source_id
    )
  order by score desc, chunk.chunk_index asc
  limit least(
    greatest(
      coalesce(p_match_count, 8),
      1
    ),
    20
  );
$$;


revoke all
on function public.search_ai_document_chunks(
  text,
  integer,
  uuid
)
from public;

grant execute
on function public.search_ai_document_chunks(
  text,
  integer,
  uuid
)
to authenticated;


-- ============================================================
-- VECTOR RETRIEVAL
-- Becomes active after real embeddings are stored.
-- ============================================================

create or replace function
public.match_ai_document_chunks(
  p_query_embedding extensions.vector,
  p_match_count integer default 8,
  p_min_similarity real default 0,
  p_source_id uuid default null
)
returns table (
  chunk_id uuid,
  document_id uuid,
  source_type text,
  source_id uuid,
  title text,
  subject text,
  content text,
  metadata jsonb,
  similarity real
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    chunk.id,
    document.id,
    document.source_type,
    document.source_id,
    document.title,
    document.subject,
    chunk.content,
    chunk.metadata,
    (
      1 - (
        chunk.embedding <=>
        p_query_embedding
      )
    )::real as similarity
  from public.ai_document_chunks chunk
  join public.ai_documents document
    on document.id = chunk.document_id
  where
    document.status = 'ready'
    and p_query_embedding is not null
    and chunk.embedding is not null
    and (
      1 - (
        chunk.embedding <=>
        p_query_embedding
      )
    ) >= coalesce(p_min_similarity, 0)
    and (
      p_source_id is null
      or document.source_id = p_source_id
    )
  order by
    chunk.embedding <=>
      p_query_embedding
  limit least(
    greatest(
      coalesce(p_match_count, 8),
      1
    ),
    20
  );
$$;


revoke all
on function public.match_ai_document_chunks(
  extensions.vector,
  integer,
  real,
  uuid
)
from public;

grant execute
on function public.match_ai_document_chunks(
  extensions.vector,
  integer,
  real,
  uuid
)
to authenticated;


notify pgrst, 'reload schema';
